function [] = generateC(name, inputs, outputName, outputFilename, matlabFileName)
    % make helper variable
    maple( [name 'Eq:=' name ';'] );
    
    % make procedure
    maple( [name 'Eq:=codegen[makeproc](' name ', ' inputs ', '...
            'locals=[A::numeric]);'] );
    
    % optimize code
    maple( [name 'Eq:=codegen[optimize](' name 'Eq);'] );
    
    % copy to name
    maple( [outputName 'Double:=copy(' name 'Eq);'] );
    maple( [outputName 'Float:=copy(' name 'Eq);'] );
    maple( [outputName ':=copy(' name 'Eq);'] );
    
    maple( ['CodeGeneration[C](' outputName 'Double, ' ...
            'defaulttype=numeric, ' ...
            'deducetypes=false, ' ...
            'output="' outputFilename '");'] );
    maple( ['CodeGeneration[C](' outputName 'Float, ' ...
            'defaulttype=numeric, ' ...
            'deducetypes=false, ' ...
            'precision=single, ' ...
            'output="' outputFilename '");'] );
    maple( ['CodeGeneration[Matlab](' outputName ', ' ...
            'defaulttype=numeric, ' ...
            'deducetypes=false, ' ...
            'output="' matlabFileName '");'] );
end